name: ci
on: [push, pull_request]
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: dtolnay/rust-toolchain@stable
            - name: Build & Test
              run: |
                  cargo fmt --all -- --check
                  cargo clippy --all -- -D warnings
                  cargo test --all --all-features
